on: [push]

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: A job to run jmeter
    steps:
    - name: Run jmeter step
      uses: kamipatel/jmeteraction@v121
      with:
        name: homework
        path: math-homework.txt
    - shell: bash
      run: |
        ls homework
