on: [push]

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: kamipatel/jmeteraction@v11
      with:
        name: dist
        path: dist
    # Use the output from the `hello` step
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: output/test/code-coverage.html
 